apiVersion: v1
kind: Pod
metadata:
  name: db-client
spec:
  containers:
    - name: db-client-container
      image: mariadb:10.7  # 클라이언트 용도로도 사용 가능, 또는 mariadb-client 이미지 사용 가능
      command: ["sleep", "3600"]  # 디버깅 또는 테스트용으로 컨테이너를 유지
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
