apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    # IRSA 역할 연결 (Terraform/IAM Role에서 만든 external-dns-irsa 사용)
    eks.amazonaws.com/role-arn: arn:aws:iam::390403881443:role/external-dns-irsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.14.0
          args:
            # AWS Route53 provider 사용
            - --provider=aws
            # Ingress & Service 모두 감시
            - --source=ingress
            - --source=service
            # 레코드 충돌 방지용 TXT 레코드
            - --registry=txt
            - --txt-owner-id=gachonlink-eks
            # 관리할 도메인 (필요한 도메인만 필터링)
            - --domain-filter=studylink.click
            - --domain-filter=gachon.studylink.click
            # 삭제 방지 (안전)
            - --policy=upsert-only
            # 공개 Hosted Zone만 대상
            - --aws-zone-type=public
          env:
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-2
