apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debug
spec:
  containers:
    - name: debug-container
      image: nugulsuhan/nugul_repo:v1     # 네트워크 디버깅용 이미지
      command: [ "sleep", "infinity" ]  # 무한 대기 (죽지 않음)
      tty: true
      stdin: true
  restartPolicy: Never
